server:
    port: 8091
eureka:
    client:
        serviceUrl:
            defaultZone: http://64.137.188.35:8761/eureka
spring:
    application:
        name: employee-consumer
    cloud:
        stream:
            kafka:
                streams:
                    binder:
                        serdeError: sendToDlq
                binder:
                    brokers: 64.137.188.35:9092
                    auto-create-topics: true
                bindings:
                    greetings-out:
                        consumer:
                          enableDql: true
                          dlqName: dead-out
                          autoCommitOnError: true
                          autoCommitOffset: true
            bindings:
                greetings-out:
                    destination: greetings-out
                    contentType: application/json
    kafka:
      consumer:
        group-id: A