server:
    port: 8091
eureka:
    client:
        serviceUrl:
            defaultZone: http://64.137.188.35:8761/eureka
spring:
  application:
    name: employee-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
        bindings:
          input:
            consumer:
              enableDlq: true
              dlqName: dead-out
              autoCommitOnError: true
              autoCommitOffset: true
      bindings:
        input:
          group: so51247113
          destination: greetings-out
          contentType: application/json
  kafka:
     consumer:
        group-id: A